### ISSUE TITLE
[PS6000]_lowLevelSetTriggerChannelConditions

### ISSUE THREAD

**Issue by PeterPablo** [colinoflynn/pico-python#100]
Hi,
did in the meanwhile anybody have a go at implementing the trigger channel conditions (function ps6000SetTriggerChannelConditions())? I'm interested setting up a trigger condition that triggers immediately and thought I might obtain the required behavior by setting PS6000_CONDITION_DONT_CARE on all channels.
[This](https://raw.githubusercontent.com/picotech/picosdk-ps6000-matlab-instrument-driver/master/glnxa64/ps6000MFile.m) MATLAB file from picotech helps with the definition of the different constants.

Background: I want to use the internal AWG and have a software trigger that starts the waveform acquisition at the same time. Up to now I did not find a solution.

Thank you!

**Comment by PeterPablo** [comment]
Thank you for getting back to me so quickly. From reading the manual I got
the impression it is not possible to use the software trigger for the
acquisition /capturing. That would indeed be simplest and exactly what I
want to achieve.

Yes, I already had a look at the scripts and probably will tackle this at
some point, though wanted to check the state of affairs first.

Am 25.10.2017 18:56 schrieb "Mark Harfouche" <notifications@github.com>:

**Comment by hmaarrfk** [comment]
I'll have to check when my computer goes back online. Waiting for some hardware to arrive but I should be able to see my code and exactly how I implemented.

An alternative would be to put an arduino onto the AUX connection and make the arduino issue a trigger on that port.

**Comment by PeterPablo** [comment]
I had a look at the manual (again) and it states for `ps6000SetSimpleTrigger()`:
```
source: the channel on which to trigger. This can be one of the four
input channels listed under ps6000SetChannel, or
PS6000_TRIGGER_AUX for the AUX input.
```

So I fear this won't work as hoped, except for introducing additional hardware that activates the trigger via AUX. Hopefully you or somebody else proves me wrong. 😃

**Comment by hmaarrfk** [comment]
Ok I guess I lied.

My memory seems to have come back. My AWG was broken on my scope so I eventually ended up giving up on using my PS6000. You should ask them on their forum if this feature is available. They are quite responsive. They might even give you a beta version of the software that enables it if it isn't already implemented.

**Comment by PeterPablo** [comment]
I wanted to post feedback that I got it to work using `TriggerAux (PS6000_TRIGGER_AUX)` as trigger source for the channel and `ScopeTrig` for the AWG. Interestingly I received the error `PICO_WARNING_AUX_OUTPUT_CONFLICT -- AUX cannot be used as input and output at the same time` on using `AuxIn (PS6000_SIGGEN_AUX_IN)` for the AWG, which would be the sensible choice for me. It seems that `TriggerRaw (PS6000_SIGGEN_TRIGGER_RAW)` can also be used though option isn't encouraged in the manual.

I posted to the PicoTech forum regarding software triggering the acquisition, though that post is not yet visible.

I am willing to close this issue as my need for the advanced triggers has now vanished. Opinions?

Thanks again for your input!

**Comment by hmaarrfk** [comment]
Lets leave it up for a few weeks. If you get feedback that indicates that we can add a hidden option then it might be good.

**Comment by hmaarrfk** [comment]
@PeterPablo, is this still an issue?

**Comment by PeterPablo** [comment]
Thanks for getting back to me. Yes, this is still an issue, but I have the impression this is (currently) a limitation of the PicoScope's firmware. The workaround of using the external trigger to trigger both signal excitation and acquisition works as expected.

**Comment by hmaarrfk** [comment]
Alright, I'm going to close this issue then.
