### ISSUE TITLE
No PicoScope XXXX could be found.

### ISSUE THREAD

**Issue by lintongtc** [colinoflynn/pico-python#103]
I installed the packages following the steps but cannot find the picoscope. I am using 5444B in Anaconda2 spyder 3.1.3 (Python 2.7-64-Win10-64), but failed to find the picoscope.

I followed the link https://github.com/colinoflynn/pico-python/issues/35 but the error remained.

### I also tried with the other link attached below and copied the ps5000a.dll to "site-packages\picoscope-0.1-py2.7.egg\picoscope\" and "site-packages\picoscope". Still it cannot work. 
Can anyone help me figure out how to find the Picoscope? Thanks very much.

===============
[https://forum.newae.com/viewtopic.php?f=7&p=763]
)Re: Urgent help: Using picoscope with Capture software

 #763  by coflynn 
 Fri Mar 04, 2016 9:59 am
Hi Kea,

It looks like it's having trouble finding the DLL. 

You need to install the PicoScope SDK from https://www.picotech.com/downloads - select your specific scope, and select the "PicoSDK (32-bit)". Once you install that it should pick the DLL up I think, although it's possible it needs to be copied into directory of picoscope .py files ("C:\WinPython-32bit-2.7.6.4\python-2.7.6\lib\site-packages\picoscope-0.1-py2.7.egg\picoscope\" it looked like on your system).

Let me know what happens!

-Colin
===============

**Below is the error information:**

PS6000 AWG Demo.

By: Mark Harfouche

This is a demo of how to use AWG with the Picoscope 6000
It was tested with the PS6403B USB2.0 version

The AWG is connected to Channel A.
Nothing else is required

Warning, there seems to be a bug with AWG
see http://www.picotech.com/support/topic12969.html

Attempting to open Picoscope 6000...
Traceback (most recent call last):
  File "D:\Google Drive D\Experiments\pico-python-master\examples\awgdemo_5000.py", line 32, in <module>
    ps = ps5000a.PS5000a()
  File "C:\Users\Lin Tong\Anaconda2\lib\site-packages\picoscope\ps5000a.py", line 140, in __init__
    super(PS5000a, self).__init__(serialNumber, connect)
  File "C:\Users\Lin Tong\Anaconda2\lib\site-packages\picoscope\picobase.py", line 134, in __init__
    self.open(serialNumber)
  File "C:\Users\Lin Tong\Anaconda2\lib\site-packages\picoscope\picobase.py", line 798, in open
    self._lowLevelOpenUnit(serialNumber)
  File "C:\Users\Lin Tong\Anaconda2\lib\site-packages\picoscope\ps5000a.py", line 162, in _lowLevelOpenUnit
    self.checkResult(m)
  File "C:\Users\Lin Tong\Anaconda2\lib\site-packages\picoscope\picobase.py", line 840, in checkResult
    raise IOError('Error calling %s: %s (%s)' % (str(inspect.stack()[1][3]), ecName, ecDesc))
IOError: Error calling _lowLevelOpenUnit: PICO_NOT_FOUND (No PicoScope XXXX could be found.)
Exception IOError: IOError(u'Error calling _lowLevelCloseUnit: PICO_INVALID_HANDLE (There is no device with the handle value passed.)',) in <bound method PS5000a.__del__ of <picoscope.ps5000a.PS5000a object at 0x00000000085A8DA0>> ignored

**Comment by hmaarrfk** [comment]
Hi Kea,
What version of the software are you using?
The PyPi library is quite old. Colin seems to have left and he holds the password to the library.

I tried to get in touch with him, but he seems not to be on GitHub.

Can you try to follow the instructions to "install from git"

You can install git from anaconda

`conda install git`

and then pull using `https `if you don't have a `git `account.

**Comment by lintongtc** [comment]
**I had a hard time dealing with it. Now I solve them one by one.

First, the Anaconda has a bug, which needs to be fixed.
I quote it below:**
"If you are using a special version of Python [like Anaconda] and you can't fix it.
Navigate to line 362 of lib/ctypes/init.py and change it to:
self._handle = _dlopen(str(self._name), mode)
From <https://github.com/pymedusa/Medusa/issues/1843> 
"

**Second,  the picoscope softwares fail to detect the scope
I solve it by installing the software in the CD rom, then upgrade it to the latest version. Previously, I tried install and uninstall the stable and beta versions, it did not work.** 

**Third, do not open Picoscope when you try to use python codes to connect. Otherwise, you will encounter the following error**
"IOError: Error calling _lowLevelOpenUnit: PICO_NOT_FOUND (No PicoScope XXXX could be found.)
"

**Comment by hmaarrfk** [comment]
Ah ok.

Got it. Thanks. Seems like an Anaconda bug that will be fixed soon.

Installing drivers is ALWAYS a pain. I'll add a note in the README
