### ISSUE TITLE
Setup travisCI to automatically push new tags to PyPi

### ISSUE THREAD

**Issue by hmaarrfk** [colinoflynn/pico-python#112]
@colinoflynn, you would need to open an account with Travis and add a travis.yml file that you can copy from me.

https://github.com/hmaarrfk/pico-python

**Comment by colinoflynn** [comment]
In theory this is on now. Until new push won't see any build attempts.

**Comment by hmaarrfk** [comment]
Awesome, I had to update my password as I think it uses the repo in the salt for PyPi. This will make our lives easier. Thanks!

https://docs.travis-ci.com/user/deployment/pypi/

**Comment by hmaarrfk** [comment]
Ok, it works now. Thanks.

I also setup travis to run flake8 which should find some syntax errors.

There are some issues with deployment still. 
Since multiple builds try to deploy the source, it is kinda problematic.
