### ISSUE TITLE
Can we avoid plotting the "picoscope" logo

### ISSUE THREAD

**Issue by ljpguimen** [colinoflynn/pico-python#122]
Hi,

The picoscope logo is plotted at the beginning of the code "ps2000_demo.py" by:
ps = ps2000a.PS2000a()
This is fancy and shows credits to Picoscope, but could introduce extra time to make the plot. It becomes a problem when repeated data are to take and makes the loop extremely slow. Is it possible to not plotting the logo - to be specific, where does the code for plotting locate?

Thanks

**Comment by hmaarrfk** [comment]
Our code is just a wrapper for their C code.

We don't add the wrapper.

If you want to remove that, you will have to talk to them on their forum or by email.
