### ISSUE TITLE
Unable to connect to Picoscope 3406

### ISSUE THREAD

**Issue by hadisajj2** [colinoflynn/pico-python#125]
I have a PicoScope 3406DMSO model. According to [this ](https://www.picotech.com/support/viewtopic.php?f=17&t=36651&view=unread#unread) forum question, I need to use the code for PS3000a series (and not PS3000). I was able to get the example C code from [here](https://github.com/picotech/picosdk-c-examples/tree/master/ps3000a) to work using visual studio and got my piscoscope to flash. 

However, I cannot get just_get_connected.py to pick up a handle. Line 17 
 `lib.ps3000aEnumerateUnits(byref(count), byref(serials), byref(serialLth))`
will return `count = 1`, meaning that it recognizes that a picoscope is connected, however, 
```python
m = lib.ps3000aOpenUnit(byref(handle), byref(s))
```
returns handle = 0

Meaning that it can't find my picoscope. 

Ironically, if I have the Pico 6 software running, it properly connects to the picoscope, and if I run the `just_get_connected.py` code, when Pico 6 is running, the handle returns a -1, which means that it found it but couldn't connect to it.

Is there anything I'm doing wrong? Are there are steps to be taken with regards to power usage? I tried with both using an adapter and not-using an adapter (letting the USB power it).

**Comment by hmaarrfk** [comment]
can you search for instances of `ps3000.dll` and `ps3000a.dll`?

Do you know your serial number? It seems like you are passing it as a parameter? Try providing it a null string. Please see the code we wrote `https://github.com/colinoflynn/pico-python/blob/master/picoscope/ps3000a.py#L151` as an example of the logic sequence.

**Comment by hadisajj2** [comment]
The issue was due to not passing null. Resolved now, thank you.
