### ISSUE TITLE
_lowLevelEnumerateUnits: ps6000EnumerateUnits NULL validity

### ISSUE THREAD

**Issue by JohnDMcMaster** [colinoflynn/pico-python#137]
_lowLevelEnumerateUnits() calls ps6000EnumerateUnits() with parameters that seem to be causing it to fail. See my post on the picoscope forum with additional details: https://www.picotech.com/support/post134781.html?sid=2452f9c184c30325fe7ef5d20feabd2c#p134781

Sounds like this is expected behavior but maybe it worked in the past? IMHO their API broke, but I guess they don't see it that way. In any case I can give a PR with a workaround if that's of interest. Basically you need to do something like this:

```
-        m = self.lib.ps6000EnumerateUnits(byref(count), None, None)
+        serials = c_int8(0)
+        serialLth = c_int16(0)
+        m = self.lib.ps6000EnumerateUnits(byref(count), byref(serials), byref(serialLth))
```

**Comment by hmaarrfk** [comment]
yeah, i noticed that some of the picotech API required references for optional parameters. They probably got tired of checking for NULL. I would accept this PR.

**Comment by davidelbaze** [comment]
Do you need someone to write the PR ? :)

**Comment by JohnDMcMaster** [comment]
Hi @davidelbaze ! I've cleaned up my patch and created the PR. However I haven't tested it. Feel free to collaborate with the devs if you think its good to merge in

**Comment by davidelbaze** [comment]
Oh fine! Thanks a lot @JohnDMcMaster, you're fast.

I'll try what's in your PR and give a comment on.
