### ISSUE TITLE
Using Anaconda/Conda Solution

### ISSUE THREAD

**Issue by henkphilipsipl** [colinoflynn/pico-python#141]
Using Anaconda/Conda
Seems like Anaconda has an issue with ctypes. See the comment here imdatacenters says to:

If you are using a special version of Python [like Anaconda] and you can't fix it. Navigate to line 362 of lib/ctypes/init.py and change it to: self._handle = _dlopen(str(self._name), mode)

**Solution, install Anaconda 32 bit. this will solve the problem  Python 3.7
Anaconda3-5.3.0-Windows-x86**
https://www.anaconda.com/download/#windows

**Comment by hmaarrfk** [comment]
Is this related to: https://github.com/colinoflynn/pico-python/issues/103  ?

**Comment by hmaarrfk** [comment]
And it seems that updating python solves things? https://github.com/pymedusa/Medusa/issues/1843#issuecomment-362492319  but maybe that is for 2.7

**Comment by hmaarrfk** [comment]
Interesting. Well if you are stuck on 32 bit, You have my sympathies.

**Comment by hmaarrfk** [comment]
Closing as this is quite old and maybe not relevant anymore
