### ISSUE TITLE
How to set MAX Sampling interval to 5ns for 2205A

### ISSUE THREAD

**Issue by AntonyLHart** [colinoflynn/pico-python#146]
Hi, I have dived into picobase.py and ps2000.py to try and resolve this, not having much luck and am hesitant to make changes. According to the picoscope 2000 series datasheet the 2205a should be capable of 200Ms/s, which indicates that it could potentially run at a sampling interval of 5ns not 10ns like the 2204a.

see:
    def setSamplingInterval (picobase.py)

When running the ps2000_demo.py, the following is printed:
    
    Found the following picoscope:
    DriverVersion                 : PS2000 Linux Driver, 2.1.6.5
    USBVersion                    : 2.0
    HardwareVersion               : 17
    VariantInfo                   : 2205A
    BatchAndSerial                : FZ011/387
    CalDate                       : 21Aug18
    ErrorCode                     : 0
    KernelVersion                 : 0.0
    Sampling interval = 10.000000 ns
    Taking  samples = 38
    Maximum samples = 8064

Do you have a possible suggestion for achieving a 5ns sampling interval?

**Comment by hmaarrfk** [comment]
By diving into the code, you should see that we don't do magic here. We just call the C driver but convert python things, into C things.

If there is a function we don't implement, you can try calling it youself by accessing the `lib` variable and the `handle`

See for example:
https://github.com/colinoflynn/pico-python/blob/master/picoscope/ps2000a.py#L208

You might get better help posting on picoscope's forums.
