### ISSUE TITLE
pico-python vs. official & ownership

### ISSUE THREAD

**Issue by colinoflynn** [colinoflynn/pico-python#147]
I haven't been involved with this project in earnest for some time despite it staying on my github. While I'd love to keep the credit for it, this seems unfair. So I wanted to check/discuss publicly two things, which are a little inter-related.

1) Transferring repo to @hmaarrfk . This can easily be done now without problem, but bringing up the future also has another point that I question: 

2) Is there functionality in this repo not existing in the official picoscope interface, now that they have put one in place? The API is different I know, but beyond that I haven't looked in much detail.

**Comment by hmaarrfk** [comment]
1. I think it is fine to keep it here. You can move it to an other organization (pico-python) that we both have ownership if you want. That way we won't keep transferring the repo around. Transfers break CI services.

2. I think the API that is probably most similar is the anyscope API they have. From taking a quick look, their API isn't really Pythonic. It isn't something I would have used without writing pico-python around it anyway.

https://github.com/picotech/picosdk-python-wrappers/blob/master/ps3000aExamples/ps3000aBlockExample.py

**Comment by colinoflynn** [comment]
Ha - alright, then status quo is easiest? We can setup an org if you want, but if it does break stuff then I'm happy to just keep it here for now. I'm not sure if the org involves different github account types etc that adds another layer of complexity.

Thanks for your comments! I had been thinking of it for a bit so glad to get your input.

**Comment by hmaarrfk** [comment]
I would setup an org if somebody else wants to do some major overhauls to it. Seems like the SDK has been pretty stable though, so seems moot.

I linked to the official SDK mostly to keep people in the loop.

Personally, I feel like they should have just built on this library, which is pretty permissively licensed. oh well.
