### ISSUE TITLE
PS6000 _lowLevelGetValuesBulk pointer error

### ISSUE THREAD

**Issue by James-Archer** [colinoflynn/pico-python#149]
I get the following error when using the bulk data function:

`in _lowLevelGetValuesBulk`
`    overflow.cytpes.data_as(POINTER(c_int16))`
`OSError: exception: access violation writing 0x0000000007A0040`

The segment of code that calls it is:

`out = self.ps.getDataRawBulk(
                        i,
                        numSamples = self.scope_samples,
                        fromSegment = 0,
                        toSegment = n-1
                    )[0]
`

This error only occurs when I am using three channels (triggering off one of them) and on the second time I call runBlock().

**Comment by hmaarrfk** [comment]
You need to keep a reference to the data arrays yourself. I think maybe the class could keep a reference for you. A contribution would be welcome

**Comment by James-Archer** [comment]
Do you mean the overflow data array? I'm not to familiar with pointers and such. My guess is that I need to reference the same data array each time we call GetDataRawBulk? And the pointer needs to point to the same array each time.

**Comment by hmaarrfk** [comment]
Can you please copy and paste a simple script that recreates the problem??? Ideally it should be less than 10 lines long, including import statements ;).

My suspicion is that you have code like (psuedocode because I haven't used this library in a while):

```python
pico = open_pico()

def foo_add_buffers(pico, size):
    buff = np.zeros(size)
    pico.set_buffer(buff)
    return    # notice that nothing is claiming a reference on buff, therefore, buff will get deleted


foo_add_buffers(pico, MY_SIZE)

acquire_data(pico)
```

It will cause a segmentation fault because the buffer gets deleted .
you need to make sure you don't delete the numpy buffer `buff` from your scope. Really, the function should "save a reference for you", to protect you against that. But I wasn't smart enough at the time.

it should be something like

```
def set_buffer(self, buffer):
    self._buffer = buffer    # see now the python object keeps a reference, and buffer will never be deallocated.
    [...] continue regular buffer setting
```

If you watn to make a PR suggesting this change, I would be glad to review it and incorporate it.

**Comment by James-Archer** [comment]
In attempting to recreate the problem it seems to be working fine in the minimal example. I'll comb over my implementation to see if I can resolve the issue.

**Comment by James-Archer** [comment]
I have a working example for the issue: 

```
from picoscope import ps6000
from time import sleep
import numpy as np

class Test():
    
    def __init__(self):

        self.ps = ps6000.PS6000()
        self.ps.setSamplingFrequency(100000, 1000)
        self.ps.setChannel('A', enabled=True)
        self.ps.setChannel('B', enabled=True)

    def GetData(self):
        segs = 10
        self.ps.setNoOfCaptures(segs)
        self.ps.memorySegments(segs)
        self.ps.runBlock()
        while not self.ps.isReady():
            sleep(0.1)
        for j, channel in enumerate(['A', 'B']):
            print(channel)
            out = self.ps.getDataRawBulk(
                    channel,
                    numSamples = 1000,
                    fromSegment = 0,
                    toSegment = segs - 1
                )
        
    def RunScan(self):
        for i in range(2):
            self.GetData()

t = Test()
t.RunScan()
t.ps.close()
print("Done")
```

It is definitely the functions that cause the issue, as putting the code from `GetData` in the `RunScan` function operates fine.

Just to be clear, are you suggesting to save the buffer in the picobase class when it is set? I've tried that by adding a `self._overflow` value in the `picobase.getDataRawBulk` function, which is where the overflow array is handled. I also tried saving the pointer in the lowlevel function as well. Neither solved the issue.

**Comment by hmaarrfk** [comment]
yeah, i'm not sure sorry. seems like you know what you are doing in terms of the driver.

We don't do much magic here, so you should be able to follow the C example  quite closely.

Did you update your drivers?

Lastly, if it persists, try to set some buffer pointers to Null after the acquisition. That fixed things for me at some point. Maybe.

I don't have a scope anymore, so it is difficult for me to tests.

Finally, if you can recreate the issue in C, then file a bug report?

**Comment by James-Archer** [comment]
Thanks for the help, I'll try those. Seem like a very obscure issue.

**Comment by James-Archer** [comment]
According to my previous comment, moving the call to `getDataRawBulk` into the same function as the loop fixes the issue, so I've gone with that solution. Still unsure about the underlying cause of the original problem, but I don't think it's significant enough to warrant any further investigation. Thanks for the support.

**Comment by hmaarrfk** [comment]
I kinda disagree..... this seems like a new segfault waiting to happen at some other time. Either way whatever works for you.
