### ISSUE TITLE
windll.LoadLibrary could not find the picoscope .dll directory

### ISSUE THREAD

**Issue by PetSven** [colinoflynn/pico-python#155]
When try to connect to my picoscope, line 137 in ps200a.py give me an error:

> File "C:\Users\psvendsen\AppData\Local\Programs\Python\Python38\lib\site-packages\picoscope\ps2000a.py", line 137, in __init__
    self.lib = windll.LoadLibrary(str(self.LIBNAME + ".dll")) 
> FileNotFoundError: Could not find module 'ps2000a.dll'. Try using the full path with constructor syntax.

To fix this, I changed line 137 from: 
` self.lib = windll.LoadLibrary(str(self.LIBNAME + ".dll"))`
To: 
`self.lib = windll.LoadLibrary("C:\\Program Files\\Pico Technology\\SDK\\lib\\ps2000a.dll")`

The code is working now, but I am wondering why it could it not find the folder with the dll files by itself? That folder is in my path variables (if that matters).

**Comment by hmaarrfk** [comment]
Are you running a 64 bit system or 32 bit?

**Comment by PetSven** [comment]
64 bit

**Comment by hmaarrfk** [comment]
I think you may have installed the 32 bit version of the picoscope library. Can you double check? Usually things are installed in program files x64

**Comment by PetSven** [comment]
I have the 64-bit version of the Picoscope SDK installed. I have the normal picoscope 6 software which looks like it is 32-bit.

**Comment by SadCl0wn** [comment]
It could also be that your python is x32

**Comment by hmaarrfk** [comment]
I'm not too sure why it didn't work for you.

I remember having trouble with getting DLLs to be found when we started this.

I basically reinstalled it and it was found. Something about environment variables probably.

That said, I may be tempted to add a few try catch statements to attempt to load the dll from a list of known directories.

**Comment by hmaarrfk** [comment]
A PR is welcome for that addition if reinstalling the sdk doesn't work

**Comment by PetSven** [comment]
> It could also be that your python is x32
I am using Python 3.8, 64 bit

**Comment by hmaarrfk** [comment]
In either case:

1. I would ask that you please reinstall Picoscope's libraries if you are so inclinde.
2. If that doesn't work, then a PR to search throug ha few directories would be reviewed and ultimately accepted in if you made it.

We had a similar issue with MacOSx, ultimately, it was decided that the problem was beyond our library, and that upstream or MacOSX should change. You can see it as the only live PR at the moment.

**Comment by hmaarrfk** [comment]
i assume you got things working?

**Comment by hmaarrfk** [comment]
I think I hit a similar bug for an other project I was working on.

IT seems that on python 3.8, you probably need a call to `find Library` before opening the library
https://github.com/conda-forge/zaber-motion-feedstock/blob/master/recipe/no_bindings_install.patch#L37

A PR with somebody that can test this would be appreciated

**Comment by klaasdc** [comment]
With Python 3.8 on x64, I had to add the following to get around this error:
```
import ctypes.util
from ctypes import cdll
...
lib_name = ctypes.util.find_library("ps2000a.dll")
cdll.LoadLibrary(lib_name)
```

**Comment by gandy92** [comment]
I just ran into the same problem. Even with the call to find_library(), it only succeeds if the required dll is in the system path. I could resolve it with the following function:
```python
def check_ps_path():
    import sys
    import os
    import glob
    import logging
    log = logging.getLogger(__file__)

    sys_path = [elem for elem in os.environ['PATH'].split(os.pathsep) if elem]

    if sys.platform == 'win32':
        for path in ['C:\\Prog*\\Pico*\\SDK\\lib\\ps6000.dll']:
            for elem in glob.glob(path):
                elem = os.path.dirname(elem)
                # if elem not in sys_path:
                sys_path.insert(0, elem)
                log.debug('Found library in {}'.format(elem))
    os.environ['PATH'] = os.pathsep.join(sys_path)
```
you may want to modify and/or extend the array of glob patterns according to your needs.

**Comment by hmaarrfk** [comment]
The call to find library should be in version 0.17.2 https://github.com/colinoflynn/pico-python/pull/167#issuecomment-706435646

If tighter integration into the rest of the python ecosystem is important to you, without managing the path yourself, then I would suggest raising the issue upstream. I'm not a fan of adding this kind of "path hunting + automagic detection" code into this library.

I assume that they now should have instructions for how to integrate into python seamlessly. This project the creation of their own library.

I'm going to close this issue as the original issue has been addressed.

Please do open an other issue if you feel like path detection is important.
