### ISSUE TITLE
setChannel AC coupling quirk

### ISSUE THREAD

**Issue by CreateRemoteThread** [colinoflynn/pico-python#161]
I stumbled into a quirk using a ps6000 with AC coupling - the first capture after setChannel needs to be discarded. I came across [this forum post](https://www.picotech.com/support/topic35401.html), indicating that you need to call runBlock before the channel setting is actually passed to the oscilloscope - but from my brief testing, this only seems to happen if AC coupling is selected.

I'm not sure what models are affected, the forum thread indicates 5xxx as well

Happy to put together a PR but I'm not sure what's the right approach here - surprise calling runBlock on a user's behalf seems a bit unsafe?

**Comment by hmaarrfk** [comment]
This seems out of scope for this library. 

We don't have much documentation as things all functions are the same as their upstream counterparts.

Happy to keep this information in a section of the readme.
