### ISSUE TITLE
Migrate to travis-ci.com

### ISSUE THREAD

**Issue by hmaarrfk** [colinoflynn/pico-python#172]
@colinoflynn do you mind migrating the repository to travis-ci.com

https://travis-ci.com/account/repositories

click on migrate

and you should be able to migrate it.

Thanks!

**Comment by colinoflynn** [comment]
Office move in process so slower on everything lately - I started the process I think (installing GH side), just as a heads up I didn't totally ignore it...

**Comment by hmaarrfk** [comment]
It should be as easy as going to travis-ci.org and clicking migrate. They ahve a bunch of warnings telling you that they are offline, but I think I was able to migrate an other one of my repos last week.

Exciting to move offices!

**Comment by colinoflynn** [comment]
OK happened now - nothing came up at first, I just checked back and it showed up! I think it migrated now (saw some of the warnings)...

Yeah exciting to be in a newer space (especially for some of our production), but moving stuff always distracts from "real" work!

**Comment by hmaarrfk** [comment]
Thanks!
