### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by bmoneke** [colinoflynn/pico-python#185]
Would it be possible to create a new release, including the new ps6000a drivers class?

**Comment by hmaarrfk** [comment]
hmmm seems like the CI pipeline I had built in the past isn't really working. I'll have to pull a modern one from a more active project of mine...

**Comment by bmoneke** [comment]
Ok, thanks.

**Comment by hmaarrfk** [comment]
progress in https://github.com/colinoflynn/pico-python/pull/187

**Comment by hmaarrfk** [comment]
0.7.22 is out now.

**Comment by bmoneke** [comment]
Thank you very much!
