### ISSUE TITLE
Needs testing: BWLimit for ps5000a

### ISSUE THREAD

**Issue by hmaarrfk** [colinoflynn/pico-python#55]
Hi,

If somebody could test the BWLimit function for the PS5000a that would be great.
It is in the branch ps5000aBWLimit

I think running https://github.com/colinoflynn/pico-python/blob/master/examples/freqmeasure.py should be enough. I just want to make sure that the setChannel function isn't broken.

Thanks,

I'll pull in a few weeks if nobody has done this and see if anybody complains

**Comment by mn14tm** [comment]
Just tested it with and works fine. Only issue was colon missing in line 212 of ps5000a [end of function def _lowLevelSetBandwidthFilter(self, channel, bandwidth) ].

**Comment by mn14tm** [comment]
FYI also noticed that the example freqmeasure is not python 3 friendly - needs brackets in the print functions. Small fix but might be worthwhile?

**Comment by hmaarrfk** [comment]
thanks mn14tm, For some reason now my branch has a conflict. I'll have to look at it on a computer that actually has git on it. 

I think I fixed the print statements. That code must have been written and ran on python2. I've been trying to make it friendly across both.

**Comment by hmaarrfk** [comment]
This seems to have been merged in at some point.
