### ISSUE TITLE
Unable to run test_ps3000a.py due to missing _lowLevelSetDataBufferBulk in ps3000a

### ISSUE THREAD

**Issue by MacGyverNL** [colinoflynn/pico-python#60]
I recently stumbled on this project and decided to try to start using it, but, having never programmed these scopes directly I'm not entirely sure how to start fixing bugs like this one:

```
Time to get sweep:  0.246327161789
Traceback (most recent call last):
  File "test_ps3000a.py2", line 51, in <module>
    ps.getDataRawBulk(data=data)
  File "/usr/lib/python2.7/site-packages/picoscope/picobase.py", line 506, in getDataRawBulk
    self._lowLevelSetDataBufferBulk(channel,
AttributeError: 'PS3000a' object has no attribute '_lowLevelSetDataBufferBulk'
```

Looking through the repo only two modules implement this function. I've found no corresponding ps3000aSetDataBufferBulk in the ps3000a programmer's manual. What am I missing here? Did this test simply never run in the first place?

**Comment by hmaarrfk** [comment]
bulk functions were probably not implemented for the ps3000a

You can inspire yourself from
https://github.com/colinoflynn/pico-python/blob/e97fb8103ec5274c6e667d47d5b3553fb6ddc80c/picoscope/ps6000.py#L499

If you get it to work, you can add a pull request, include yourself in the appropriate author lists

**Comment by MacGyverNL** [comment]
They're not implemented because they don't seem to even exist in libps3000a. The programmer's manual for the 6000 series doesn't really make clear to me what the difference between using ps6000SetDataBuffer and ps6000SetDataBufferBulk is, since both apply to rapid block mode.

The libps3000a manual has a slightly different step-by-step instruction for rapid block mode, it states one should use ps3000aSetDataBuffer, where the 6000 uses ps6000SetDataBufferBulk.

However, both in the 3000a and the 6000 manuals, they state that the respective function should be called "once for each channel/segment combination for which you require data".

Comparing the functions, it seems that they dropped the version that doesn't require to specify the segment (ps6000SetDataBuffer) in the 3000a library; rather, what would've been ps3000aSetDataBufferBulk is now simply ps3000aSetDataBuffer.

So, my guess is that the issue is actually with the way that picobase.py implements getDataRawBulk; it assumes that the functions to call for rapid block mode are actually the same across all picoscope libraries, which is not the case. One solution would be to simply implement the functions that are missing or differently named with delegation in the picoscope-specific file, another would be to override getDataRawBulk if the procedure is different. What would be the preferred way here?

**Comment by hmaarrfk** [comment]
would it be possible to add a stub function
ps3000aSetDataBufferBulk (python) that just calls the ps3000aSetDataBuffer (c, or python function)
I think the compiler will just simplify them to the same thing anyway.

Do you feel like this would be a step in the wrong direction?
My fear with implementing it in ps3000a specific is that we will not remember to update it an there will be lots of duplicated code. That said, it might be worth a try, and we could deal with refractoring the code later.

I'll pull in your patch when you implement it. Add yourself to the authors/acknowledgements whatever you see fit.

**Comment by MacGyverNL** [comment]
Sure, that's option 1 I mentioned. Let's not add too much abstraction if it's not required, a simple delegation will work for those scopes which don't offer the SetDataBufferBulk in the library itself; in essence it's the same function. I've got something basic to work now, I'll clean it up and submit a patch after the weekend.
