### ISSUE TITLE
ps3000a SigGen

### ISSUE THREAD

**Issue by Drehstromlampe** [colinoflynn/pico-python#63]
_lowLevelSetSigGenBuiltInSimple() was missing from ps3000a
I added that to my local libs and would like to contribute them.
Whats the procedure for doing that?

**Comment by hmaarrfk** [comment]
Thanks for wanting to get involved.

1. Fork
2. Create a new branch with your changes
3. Follow the general coding style.
4. Add your name to the contributors/authors
5. Request to merge it with our main branch on github.

Thanks again!

**Comment by PeterPablo** [comment]
#64 seems related.

**Comment by hmaarrfk** [comment]
We just pulled in some changes made by a few contributors. You can try to uncomment the code
https://github.com/colinoflynn/pico-python/blob/master/picoscope/ps3000a.py#L379

And see if it works.

**Comment by hmaarrfk** [comment]
Seems like OP found a solution
