### ISSUE TITLE
PS4262 Compatibility?

### ISSUE THREAD

**Issue by hmaarrfk** [colinoflynn/pico-python#73]
Olivier Doaré <olivier.doare@ensta-paristech.fr>
Jan 30 (1 day ago)

to coflynn, me 
Hello,

I am planning to buy a Picoscope 4262 and would use it with Python under Linux with the help of the extensions you have developed. You don't mention this scope, but on the documentation in github, there is a part about the 4000 series. Is there any chance for it to work ?

There is also the PicoScope 5242A, which seems similar in terms of features, should I buy this one ? (I know this is a question I should ask to Picotech, hence I would understand if you ignore this one...)

Thank you for developing and sharing your work,
best regards,
Olivier Doaré

___________________________________________

Mark Harfouche <mark.harfouche@gmail.com>
Jan 30 (1 day ago)

to Olivier, coflynn 
Hi,

We do not have an extensive list of scopes that work with our code, rather just as people report it to us. 
If you see a scope that uses the same programming manual as yours, it means your scope is almost sure compatible with our code.

Have you ever programmed in C? 
If so, it should be rather straightforward to adapt the code to any oscilloscope you buy.

That said, I think it is better if you open an issue on GitHub, that way others can chime in as well.

Cheers,

Mark

Colin O'Flynn
9:43 AM (23 hours ago)

to Olivier, me 
Hi Olivier,
 
I haven’t used the 4000 series, but I think someone else added support for this scope. You’d have to check back in the GIT log to see where it came from.
 
As Mark mentioned the critical part is just if it uses the same programming manual, it should be OK. It’s not a major issue to add support, but it may require a small amount of effort on your side.
 
I’ve used the 5000-series and was very happy with it… the flexible resolution is nice rather than committing to a higher resolution but at a lower sampling rate (as in the 4262). The 4262 seems designed for some sort of specific applications (the 16-bit resolution, but very low 5 MHz bandwidth), so it might be you specifically need that?
 
Regards,
 
  -Colin O’Flynn
 

Hello,

Thanks a lot for your kind and useful responses.

5MHz is largely enough for me as my main intersest are vibration and (audible) acoustics. 16 bits are a minimum requirement, but I understand that it is possible to oversample to increanse bit depth with both cards. So in fact both options are OK for my application.

For the effort I would have to furnish to implement support for the 4262, I am unfortunately not very experienced in C programming. I would be glad to learrn, but that is a matter of time, and I unfortunately don't have a lot.

Thank you again for your responses !
Best regards,
Olivier

**Comment by hmaarrfk** [comment]
Oliver, 

I think the 4264 should be compatible. Dimitry seems to have added the functionality. https://github.com/colinoflynn/pico-python/commit/e0de1355500082fe81c82b17e35d7b5f987ac3fa
He tested it with 4424.

You don't necessarily need to know how to program in C. but it is useful if you are trying to develop reading and writing from buffers. That part seems to have been done before. Any type of experience where you have to interact with arrays will be useful. Some advanced features will require you to organize the memory of the scope.

Mark

**Comment by kloper** [comment]
I am still there and still posses good old 4424. I am not sure my port is 100% working, but I hope l be able to help you if you have any trouble.

**Comment by hmaarrfk** [comment]
Closing this as this is a future feature request. We don't support all picoscopes. Users of this scope are welcome to issue their own pull requests as they see fit.
