### ISSUE TITLE
Macos X Support

### ISSUE THREAD

**Issue by sebma** [colinoflynn/pico-python#80]
Hi,

I have installed [Picoscope Beta v6.11.13.2](https://www.picotech.com/downloads/_lightbox/picoscope6mac) (the drivers are included)

I'm using Macos X 10.12.5 and when I try to : 

`ps = ps2000.PS2000()`, I get this error : 

```
In [3]: ps = ps2000.PS2000()
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-3eb67f4a7698> in <module>()
----> 1 ps = ps2000.PS2000()

/usr/local/lib/python2.7/site-packages/picoscope/ps2000.pyc in __init__(self, serialNumber, connect)
    128             self.lib = cdll.LoadLibrary("lib" + self.LIBNAME + ".so")
    129         else:
--> 130             from ctypes import windll
    131             self.lib = windll.LoadLibrary(self.LIBNAME + ".dll")
    132

ImportError: cannot import name windll
```

Can you help me ?

**Comment by hmaarrfk** [comment]
I think you are the first person to use Mac. We have never used our code on
a Mac before. Cool!

Are you going to be using a Mac on the final machine?
If not, I recommend using the same machine as the "final" one, or at least
the same version of the same operating system. Many challenges can arise
when changing OSs.

In either case, can you give me the output of the following two commands on
your ipython console:

```python
import platform
platform.system()
```

**Comment by sebma** [comment]
Hi, cannot do it today because I'm at home and I don't have an ssh to it but.

But I have an ssh access to an older one (`Mac OS X 10.11.6`) and `platform.system()` says : 

`'Darwin'`

I've already seen this name and I'm almost positive that the mac I use at the university will answer '`'Darwin'` as well, therefore you can already start testing if `platform.system() == 'Darwin'` :-)

**Comment by hmaarrfk** [comment]
Ok you are going to have to test things for us.

I assume you know how to use git?
If you have installed our library through pip, please remove it
```sh
pip uninstall picoscope
```

Checkout the `mac` branch of our library

```sh
git clone git@github.com:colinoflynn/pico-python.git
git checkout mac
```

install the picoscope library in development mode using the mac branch:
```sh
python setup.py develop
```

You can see the difference between the `mac` branch and the `master` branch in this commit, I'll pull it in if you say that it works.

https://github.com/colinoflynn/pico-python/commit/83a5ac3a17833c923723595c7806583124cad815

**Comment by sebma** [comment]
Hi, I'm back at work :)

`git clone git@github.com:colinoflynn/pico-python.git` says : 

```
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.113' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by colinoflynn** [comment]
It should be

          git clone https://github.com/colinoflynn/pico-python.git

The ssh URL requires you to have repo access.

**Comment by sebma** [comment]
Ok, here is what I get now : 

```
$ git clone https://github.com/colinoflynn/pico-python.git
Cloning into 'pico-python'...
remote: Counting objects: 699, done.
remote: Total 699 (delta 0), reused 0 (delta 0), pack-reused 699
Receiving objects: 100% (699/699), 942.51 KiB | 0 bytes/s, done.
Resolving deltas: 100% (444/444), done.
$ git checkout mac
error: pathspec 'mac' did not match any file(s) known to git.
```

**Comment by sebma** [comment]
Ok I had to `cd pico-python` before doing the `git checkout mac`

Now I just installed  `the picoscope library in development mode`.

And when I run `ps = ps2000.PS2000()`, It now says : 

```
In [2]: ps = ps2000.PS2000()
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-2-3eb67f4a7698> in <module>()
----> 1 ps = ps2000.PS2000()

/Users/mansfeld/src/pico-python/picoscope/ps2000.py in __init__(self, serialNumber, connect)
    126         if platform.system() == 'Linux' or platform.system() == 'Darwin':
    127             from ctypes import cdll
--> 128             self.lib = cdll.LoadLibrary("lib" + self.LIBNAME + ".so")
    129         else:
    130             from ctypes import windll

/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.pyc in LoadLibrary(self, name)
    438
    439     def LoadLibrary(self, name):
--> 440         return self._dlltype(name)
    441
    442 cdll = LibraryLoader(CDLL)

/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ctypes/__init__.pyc in __init__(self, name, mode, handle, use_errno, use_last_error)
    360
    361         if handle is None:
--> 362             self._handle = _dlopen(self._name, mode)
    363         else:
    364             self._handle = handle

OSError: dlopen(libps2000.so, 6): image not found
```
By search `libps2000.*`, I found this file : 

`/Applications/PicoScope6.app/Contents/Resources/lib/libps2000.dylib`

**Comment by sebma** [comment]
I believe, maybe in `[ps2000.py#L126](https://github.com/colinoflynn/pico-python/blob/master/picoscope/ps2000.py#L126)`, you can try this : 

```
        if platform.system() == 'Linux'
            from ctypes import cdll
            self.lib = cdll.LoadLibrary("lib" + self.LIBNAME + ".so")
        elif platform.system() == 'Darwin'
            from ctypes import cdll
            self.lib = cdll.LoadLibrary("lib" + self.LIBNAME + ".dylib")
        else:
            from ctypes import windll
            self.lib = windll.LoadLibrary(self.LIBNAME + ".dll")
```

**Comment by sebma** [comment]
Ok, I found how : 

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/Applications/PicoScope6.app/Contents/Resources/lib`

and then run `ipython`

**Comment by hmaarrfk** [comment]
Hi sebma,

I assume that the two changes you did were to 

 1. use the extension `.dylib` 
 2. exporting the path

Did picoscope teach you about exporting the path? Do you have a reference for this? I would rather not duplicate install instructions that are available on the official picotech website.

Other than that, I'll try to update the libraries we have to enable Mac support.

Mark

**Comment by sebma** [comment]
`Did picoscope teach you about exporting the path? Do you have a reference for this? I would rather not duplicate install instructions that are available on the official picotech website.`

I don't understand what you mean because I don't think you need to change your install instructions at all.

Maybe if you are willing, just give a little advice in a new `README.Macos` file regarding `LD_LIBRARY_PATH` variable :)

Thanks for your time and patience.

Please me, keep me updated when you have `.dylib` extension support in your picoscope libraries.
Ok, thank

**Comment by hmaarrfk** [comment]
You didn't simply guess that you had to add this specific path:

```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/Applications/PicoScope6.app/Contents/Resources/lib
```

Was this your knowledge of software, or some instructions on the picotech website?

**Comment by sebma** [comment]
Ok, now I understand the question :) and the answer is : 

```
$ find /Applications -name "libps2000.*"
/Applications/PicoScope6.app/Contents/Resources/lib/libps2000.2.dylib
/Applications/PicoScope6.app/Contents/Resources/lib/libps2000.dylib
```

**Comment by sebma** [comment]
It's almost 8pm, so I really have to go :)

Jesus bless you !

**Comment by hmaarrfk** [comment]
Ah ok, so you hunted for the library yourself.

I'll try to push it to pip soon.

BTW, this is about as much as I can do in terms of helping you setup the MacOSX libraries.

If you want to continue fixing things up, I suggest you do the following:

  1. Fork our library
  2. Make a new branch in your version of the repository
  3. Make changes
  4. Issue a pull request once you think you've ironed out the bugs so that we can share it with the rest of the people.

**Comment by sebma** [comment]
@hmaarrfk Hi,

Unfortunatly, I don't have much time to do this at the moment because I'm already late in my tasks.

The only thing you need to do on your side is to modify from lines 126 to 131 of [ps2000.py#L126](https://github.com/colinoflynn/pico-python/blob/master/picoscope/ps2000.py#L126) using [this](https://github.com/colinoflynn/pico-python/issues/80#issuecomment-314085436) piece of code.

Add then apply that to the other libraries as well.

Maybe replace this piece of code by a function that you can call.

**Comment by hmaarrfk** [comment]
The changes were done soon after you requested them in the `mac` branch. I didn't merge them into the main branch because I wanted time to review the changes. I think I'll push them in now.

**Comment by sebma** [comment]
@hmaarrfk Thanks a lot :)

**Comment by sebma** [comment]
@hmaarrfk 
Hi, here are the two Macos X commands to add current USER to the `pico`group : 
```
# Create the new pico group :
sudo dseditgroup -o create pico
#Add the current user to the pico group :
sudo dseditgroup -o edit -a $USER -t user pico
```
You can add the them in the **[Additional Installation Information for Mac OSX](https://github.com/colinoflynn/pico-python#additional-installation-information-for-mac-osx)**.

**Comment by hmaarrfk** [comment]
Thanks.

Please create a new issue that way we keep track of the things that we still have "todo"

Mark

**Comment by sebma** [comment]
@hmaarrfk Hi,

Why not reopen this one ? It's title seems fine to me to follow the "Macos X Support" changes.

**Comment by hmaarrfk** [comment]
Reopenning issues makes them difficult to track down. While there were only 10s of comments on this one, what happens when there are 100s?

If I hadn't seen this email immediately, I would have missed your comment since Closed Issues don't appear in the same list as open issues.

If you come by this thread 5 years later, after a few versions of MacOS X have been released, is the original issue mentioned still a problem? You would have to read about 10 different issues, just to see which one you care about, and to see if it was fixed.

Anyway, it isn't that big of a deal, and this one was borderline appropriate to reopen. I could have seen it as: "your previous instructions were incomplete". But I can also see it as not an issue with our library as the first issue required changes in the code, but rather the way you installed the picotech library on your own computer.

**Comment by sebma** [comment]
@hmaarrfk Ok, now I understand. Let me change the title of this issue and also create a new one.

**Comment by sebma** [comment]
@hmaarrfk What name can I choose for the new to keep track of the things that we still have "todo" ?

**Comment by hmaarrfk** [comment]
Its fine, I fixed the Readme already.

Thanks for reporting bugs.

**Comment by sebma** [comment]
@hmaarrfk Hi,

My mistake on Macos, the name of variable containing the PATH to the libraries is not `LD_LIBRARY_PATH` but `DYLD_LIBRARY_PATH`.

Can you please change it in the README.md ?

**Comment by hmaarrfk** [comment]
Will do.

Please stop adding comments to this thread. Anything that needs a "fix" needs to be filed under a different change.
