### ISSUE TITLE
Update __init__.py with a __version__ __author__ and __license__ string

### ISSUE THREAD

**Issue by sebma** [colinoflynn/pico-python#89]
Hi,

Can you please update `picoscope/__init__.py` with a `__version__` string (i.e `0.5`) and move  `__author__` and `__license__` strings from `picoscope/picobase.py` to `picoscope/__init__.py` so they can be accessible in a stardardized way ?

**Comment by sebma** [comment]
Hi,

I didn't think you would put them in `picoscope/picobase.py`, but it's fine.

However, can you please add this line to `picoscope/__init__.py` : 

`from picoscope.picobase import __author__, __license__, __version__`

So that the version (and others) are accessible in a standardized manner : 

```
>>> import picoscope
>>> picoscope.__version__
0.6
>>> picoscope.__author__
u"Colin O'Flynn, Mark Harfouche"
>>> picoscope.__license__
u'FreeBSD'
```

It would be nice and great :)

**Comment by sebma** [comment]
@hmaarrfk 

Hi hmaarrfk,

Maybe this : [Placing metadata like __title__, __author__, __version__ etc in __init__.py](https://stackoverflow.com/questions/37989422/placing-metadata-like-title-author-version-etc-in-init-py#comment63422845_37989422) and this [What is the common header format of Python files?](https://stackoverflow.com/a/1523456) can help.

And also a piece of code to `use them in setup.py, in case the module can't be imported prior to install (missing requirements, etc.):` [parse_init()](https://github.com/textbook/atmdb/blob/master/setup.py#L19)

**Comment by sebma** [comment]
@hmaarrfk Can you also push v0.6 to the [Python Package Index](https://pypi.python.org/pypi) ?

That would be great.

**Comment by hmaarrfk** [comment]
Hey thank you very much for those links.

I'm trying to parse them now. So is the `__init__.py` file supposed to have the following lines

```python
import ps2000
import ps2000a
...
import ps6000
```

**Comment by hmaarrfk** [comment]
About pip, see Issue #86

**Comment by sebma** [comment]
@hmaarrfk Hi,

To your question : 

> So is the `__init__.py` file supposed to have the following lines
> 
> ```
> import ps2000
> import ps2000a
> ...
> import ps6000
> ```

I don't think so but maybe you can tell me where you have read this (I'm asking you this because I didn't read all the PEPs that my links pointed to)

**Comment by hmaarrfk** [comment]
I don't really have a Pep link. I'm just worried about the usability of the package.

Well right now, if you have the line
```python
import picoscope
```
it doesn't really do anything. It just gives you access to the __version__ and whatnot variables.

I imagine it should work like
```python
ps  = picoscope.PS2000a()
ps2 = picoscope.PS3000a()
```

**Comment by sebma** [comment]
In my script, here is I do : 

`from picoscope import *`

and this is only possible because of your `__all__` statement in `picoscope/__init__.py`

I don't think you need to add anything to `picoscope/__init__.py`

**Comment by sebma** [comment]
@hmaarrfk Hi,

I've installed the release 0.6 release, but then I get : 
    print(" version : %s." % picoscope.__version__)
AttributeError: 'module' object has no attribute '__version__'

Can you please create a 0.6.1 release tag that includes commit [6dee594](https://github.com/colinoflynn/pico-python/commit/6dee594fa73776aaa60a459e9280047aa2f291e6#diff-446378e59999d4d365f6efc4359e6171) ?

**Comment by hmaarrfk** [comment]
Sorry about this
https://github.com/colinoflynn/pico-python/tree/0.6.1

should work

**Comment by sebma** [comment]
@hmaarrfk Thanks :)
But now `__version__` should be `0.6.1` in `__init__.py` instead of `0.6`
I'd like to know a way to synchronize github version tags with `__version__` in `__init__.py`

**Comment by sebma** [comment]
@hmaarrfk Maybe this can help : [Single-sourcing the package version](https://packaging.python.org/guides/single-sourcing-package-version/)

**Comment by hmaarrfk** [comment]
Thanks, I opened an issue for it. Feel free to fix it and submit a pull request.

**Comment by hmaarrfk** [comment]
I think this has been fixed in recent updates. Lets open a new issue if this is still a problem.
